spring:
  application:
    name: naver-mocking-api

  datasource:
    url: jdbc:mysql://localhost:3306/naver_mock?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Seoul

server:
  port: 10000
  servlet:
    context-path: /naver-api

# JWT ??
jwt:
  secret: naver-secret-key
  expiration: 86400000 # 24??

# ?? ??
logging:
  level:
    com.market.naver: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

# Swagger ??
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html